version: '3.8'


services:
  DB:
    image: mysql:8.0
    container_name: DB
    restart: always
    env_file:
    - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
    - '3307:3306'
    volumes:
    - db_data:/var/lib/mysql
    networks:
    - sw_task_network

  web_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    env_file:
    - .env
    networks:
    - sw_task_network
    depends_on:
      DB:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate && gunicorn -w 2 -b 0.0.0.0:8000 task_core.wsgi:application"

networks:
  sw_task_network:
    driver : bridge

volumes:
  db_data:
    driver: local
